# Generated by Django 4.2.6 on 2023-11-06 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_urls'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urls',
            new_name='Url',
        ),
    ]
