# Generated by Django 4.2.6 on 2023-11-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayarlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uygulamalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
            ],
        ),
    ]
